# Generated by Django 3.0.7 on 2020-06-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teammembername', models.CharField(max_length=100)),
                ('memberexpertise', models.CharField(max_length=200)),
                ('memberdesc', models.TextField()),
                ('memberimg', models.ImageField(upload_to='pics')),
                ('memberfacebook', models.CharField(max_length=100)),
                ('membertwitter', models.CharField(max_length=100)),
                ('memberlinkedin', models.CharField(max_length=100)),
                ('membergithub', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ourprojects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ourprojects_projectname', models.CharField(max_length=100)),
                ('ourprojects_projectdesc', models.TextField()),
                ('ourprojects_projectprice', models.IntegerField()),
                ('ourprojects_review', models.IntegerField()),
                ('ourprojects_projectimg', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
